#!/bin/sh

run="/var/run/one"
lock="/var/lock/one"
user="alex"

if [ ! -d $run ]; then mkdir $run; fi
if [ ! -d $lock ]; then mkdir $lock; fi

chown -R $user:$user $run
chown -R $user:$user $lock

xinput --disable "ELAN Touchscreen"

xrandr --newmode "2560x1440-60" 241.50 2560 2608 2640 2720 1440 1442 1447 1481 +hsync +vsync
xrandr --addmode HDMI1 "2560x1440-60"
xrandr --output HDMI1 --mode 2560x1440-60 --verbose
xrandr --output HDMI1 --primary --mode 2560x1440-60 --pos 0x0 --rotate normal --output eDP1 --mode 1920x1080 --pos 256x1440 --rotate normal

sudo -H -u alex bash -c 'nitrogen --restore'
