#-------------------------------------------------------------------------------
# Theme configuration
#-------------------------------------------------------------------------------
[icons]
name = "awesome"

[theme]
name = "slick"

[theme.overrides]
idle_bg      = "#4C566A"
idle_fg      = "#ECEFF4"
#idle_bg     = "#2e3440" # nord0
#idle_fg     = "#81a1c1" # light blue
good_bg      = "#a3be86" # green
good_fg      = "#2e3440" # nord0
warning_bg   = "#ebcb8b" # yellow
warning_fg   = "#2e3440" # nord0
critical_bg  = "#bf616a" # red
critical_fg  = "#2e3440" # nord0
separator    = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

#-------------------------------------------------------------------------------
# Blocks
#-------------------------------------------------------------------------------
[[block]]
block    = "net"
device   = "wlp2s0"
format   = "{ip} [{signal_strength}]"
interval = 5

[[block]]
block    = "speedtest"
interval = 1800
format   = "{ping}{speed_down:4*B}"

[[block]]
block     = "disk_space"
path      = "/"
alias     = "/"
info_type = "available"
unit      = "GB"
interval  = 20
warning   = 20.0
alert     = 10.0
format    = "{icon} {available}"

[[block]]
block        = "memory"
format_mem   = "{mem_used}/{mem_total}"
display_type = "memory"
icons        = true
clickable    = false
warning_mem  = 80
critical_mem = 95

[[block]]
block     = "temperature"
collapsed = false
interval  = 10
format    = "{average}"
chip      = "*-isa-*"

[[block]]
block    = "time"
interval = 60
format   = "%d/%m %R"

[[block]]
block    = "uptime"
interval = 1

[[block]]
block    = "battery"
interval = 10
format   = "{percentage} {time}"

[[block]]
block    = "custom"
command  = "echo al3xhh"
interval = "once"
