#-------------------------------------------------------------------------------
# Theme configuration
#-------------------------------------------------------------------------------
[icons]
name = "awesome5"

[theme]
name = "nord-dark"

[theme.overrides]
separator    = " | "
separator_fg = "#81A1C1"

#-------------------------------------------------------------------------------
# Blocks
#-------------------------------------------------------------------------------
[[block]]
block    = "custom"
command  = "echo al3xhh"
interval = "once"

[[block]]
block    = "net"
device   = "wlp2s0"
format   = "{ip} [{signal_strength}]"
interval = 5

# [[block]]
# block    = "speedtest"
# interval = 1800
# format   = "{ping}{speed_down:4*B}"

[[block]]
block     = "disk_space"
path      = "/"
alias     = "/"
info_type = "available"
unit      = "GB"
interval  = 20
warning   = 20.0
alert     = 10.0
format    = "{icon} {available}"

[[block]]
block        = "memory"
# format_mem   = "{mem_used}/{mem_total}"
format_mem   = "{mem_used}"
display_type = "memory"
icons        = true
clickable    = false
warning_mem  = 80
critical_mem = 95

# [[block]]
# block    = "uptime"
# interval = 1

[[block]]
block    = "custom"
command  = "echo Bat0: $(cat /sys/class/power_supply/BAT0/capacity)%"
interval = 10

[[block]]
block    = "custom"
command  = "echo Mouse: $(solaar show | tail -n2 | head -n1 | cut -d ',' -f3 | cut -d '.' -f1)%"
#interval = 60

[[block]]
block    = "time"
interval = 60
format   = "%d/%m %R"

[[block]]
block     = "temperature"
collapsed = false
interval  = 10
format    = "{average}"
chip      = "*-isa-*"
